# --- !Ups
CREATE TABLE EVENT (
  EVENT_ID varchar(255) NOT NULL,
  EVENT_NAME text NOT NULL,
  EVENT_DATE date NOT NULL,
  IS_PRIVATE boolean
--  ,PRIMARY KEY (EVENT_ID)
);

CREATE TABLE ACCOUNT (
  ACCOUNT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACCOUNT varchar(255) NOT NULL,
  PRIMARY KEY (ACCOUNT)
);

CREATE TABLE EVENT_MEMBER (
  EVENT_ID varchar(255) NOT NULL,
  ACCOUNT varchar(255) NOT NULL,
  AUTHORITY TEXT NOT NULL,
  ATTEND_STATUS char(1), -- 1 参加 2 不参加 3 迷い中 0 未入力
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
  FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT(ACCOUNT)
);

--INSERT INTO EVENT (EVENT_NAME, EVENT_DATE, IS_PRIVATE) VALUES ('test', '2014-04-29', false);
--INSERT INTO ACCOUNT (ACCOUNT) VALUES ('testuser');
--INSERT INTO EVENT_MEMBER (EVENT_ID, ACCOUNT_ID, AUTHORITY) VALUES ('1', '1', 'Normal');

# --- !Downs
 
DROP TABLE EVENT;
DROP TABLE ACCOUNT;
DROP TABLE EVENT_MEMBER;
